from pathlib import Path

REFERENCES_DIR = Path(__file__).parent / "references"

DEVICE_A = "emulator-5554"
DEVICE_B = "emulator-5574"

POLL_INTERVAL_SECONDS = 0.75
SWAP_COOLDOWN_SECONDS = 5.0
MATCH_THRESHOLD = 0.85

STUCK_TIMEOUT_SECONDS = 300.0
RECOVERY_TIMEOUT_SECONDS = 60.0

LOGIN_TAP_RETRIES = 3
LOGIN_TAP_VERIFY_DELAY_SECONDS = 1.5

STAGE_CLEAR_TEMPLATE = "stage_clear"
CLEAR_BANNER_TEMPLATE = "clear_banner"
LOGIN_BUTTON_TEMPLATE = "login_button"

GAME_PACKAGE = "com.Level5.YWP"
