from pathlib import Path

REFERENCES_DIR = Path(__file__).parent / "references"

DEVICE_A = "emulator-5554"
DEVICE_B = "emulator-5574"

POLL_INTERVAL_SECONDS = 0.25
MATCH_THRESHOLD = 0.80

INITIAL_POLL_DELAY_SECONDS = 18.0

STUCK_TIMEOUT_SECONDS = 60.0
RECOVERY_TIMEOUT_SECONDS = 60.0

NTFY_URL = "https://ntfy.sh/REDACTED"
ESCALATION_TIMEOUT_SECONDS = 240.0
ALERT_REPEAT_SECONDS = 300.0
ERROR_RETRY_SECONDS = 5.0

LOGIN_BUTTON_COORDS = (525, 1187)
STAGE_CLEAR_TAP_DELAY_SECONDS = 0.02

STAGE_CLEAR_TEMPLATE = "stage_clear"
CLEAR_BANNER_TEMPLATE = "clear_banner"
LOGIN_BUTTON_TEMPLATE = "login_button"

GAME_PACKAGE = "com.Level5.YWP"
